### ISSUE TITLE
Errors when uploading multiple files in production

### ISSUE THREAD

**Issue by phebal** [galterlibrary/digital-repository#288]
Sometimes uploading more then one file throws an error about creating a generic file. See:
https://gist.github.com/pgwillia/d507299f81f7110f6530 for some info

```
I, [2015-11-02T11:31:31.787931 #10948]  INFO -- : Processing by GenericFilesController#create as JSON
I, [2015-11-02T11:31:31.788076 #10948]  INFO -- :   Parameters: {"utf8"=>"✓", "authenticity_token"=>"I4OgDOWAWJdLEK9qakuLpOgKgkq+ep/Eyw5lRWAuMNClUuOkeYG/YkIICdv56KUl+C7AvISJnCSKE+BA0gfHYw==", "total_upload_size"=>"3864357", "relative_path"=>"", "batch_id"=>"rr171x20k", "file_coming_from"=>"local", "terms_of_service"=>"1", "files"=>[#<ActionDispatch::Http::UploadedFile:0x0000000bef1338 @tempfile=#<Tempfile:/tmp/RackMultipart20151102-10948-s06r25.pptx>, @original_filename="vivo_around_the_world.pptx", @content_type="application/vnd.openxmlformats-officedocument.presentationml.presentation", @headers="Content-Disposition: form-data; name=\"files[]\"; filename=\"vivo_around_the_world.pptx\"\r\nContent-Type: application/vnd.openxmlformats-officedocument.presentationml.presentation\r\n">]}
I, [2015-11-02T11:31:31.978831 #7055]  INFO -- : Started POST "/files" for 165.124.124.27 at 2015-11-02 11:31:31 -0600
I, [2015-11-02T11:31:31.981669 #7055]  INFO -- : Processing by GenericFilesController#create as JSON
I, [2015-11-02T11:31:31.981835 #7055]  INFO -- :   Parameters: {"utf8"=>"✓", "authenticity_token"=>"I4OgDOWAWJdLEK9qakuLpOgKgkq+ep/Eyw5lRWAuMNClUuOkeYG/YkIICdv56KUl+C7AvISJnCSKE+BA0gfHYw==", "total_upload_size"=>"3864357", "relative_path"=>"", "batch_id"=>"rr171x20k", "file_coming_from"=>"local", "terms_of_service"=>"1", "files"=>[#<ActionDispatch::Http::UploadedFile:0x0000000a52de38 @tempfile=#<Tempfile:/tmp/RackMultipart20151102-7055-17d5mbw.pptx>, @original_filename="bienvenido_vivo3.pptx", @content_type="application/vnd.openxmlformats-officedocument.presentationml.presentation", @headers="Content-Disposition: form-data; name=\"files[]\"; filename=\"bienvenido_vivo3.pptx\"\r\nContent-Type: application/vnd.openxmlformats-officedocument.presentationml.presentation\r\n">]}
E, [2015-11-02T11:31:32.377954 #7055] ERROR -- : GenericFilesController::create rescued Ldp::BadRequest
        Could not remove triple containing predicate http://fedora.info/definitions/v4/repository#lastModifiedBy to node /production/rr/17/1x/20/rr171x20k
Could not remove triple containing predicate http://fedora.info/definitions/v4/repository#uuid to node /production/rr/17/1x/20/rr171x20k
Could not remove triple containing predicate http://fedora.info/definitions/v4/repository#createdBy to node /production/rr/17/1x/20/rr171x20k
Could not remove triple containing predicate http://fedora.info/definitions/v4/repository#primaryType to node /production/rr/17/1x/20/rr171x20k
Could not remove triple containing predicate http://fedora.info/definitions/v4/repository#created to node /production/rr/17/1x/20/rr171x20k
Could not remove triple containing predicate http://fedora.info/definitions/v4/repository#mixinTypes to node /production/rr/17/1x/20/rr171x20k
Could not remove triple containing predicate http://fedora.info/definitions/v4/repository#mixinTypes to node /production/rr/17/1x/20/rr171x20k
Could not remove triple containing predicate http://fedora.info/definitions/v4/repository#lastModified to node /production/rr/17/1x/20/rr171x20k
Could not remove triple containing predicate http://fedora.info/definitions/v4/repository#writable to node /production/rr/17/1x/20/rr171x20k
Could not remove triple containing predicate http://fedora.info/definitions/v4/repository#hasParent to node /production/rr/17/1x/20/rr171x20k
Could not remove triple containing predicate http://fedora.info/definitions/v4/repository#exportsAs to node /production/rr/17/1x/20/rr171x20k
The namespace prefix (fcr) has not been registered
 /var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/ldp-0.3.1/lib/ldp/client/methods.rb:108:in `block in check_for_errors'
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/ldp-0.3.1/lib/ldp/client/methods.rb:106:in `tap'
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/ldp-0.3.1/lib/ldp/client/methods.rb:106:in `check_for_errors'
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/ldp-0.3.1/lib/ldp/client/methods.rb:89:in `put'
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/active-fedora-9.1.2/lib/active_fedora/caching_connection.rb:24:in `put'
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/ldp-0.3.1/lib/ldp/resource.rb:72:in `create'
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/ldp-0.3.1/lib/ldp/resource/rdf_source.rb:21:in `create'
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/active-fedora-9.1.2/lib/active_fedora/persistence.rb:151:in `create_record'
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/active-fedora-9.1.2/lib/active_fedora/indexing.rb:45:in `create_record'
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/active-fedora-9.1.2/lib/active_fedora/callbacks.rb:237:in `block (2 levels) in create_record'
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:117:in `call'
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:117:in `call'
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:505:in `call'
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:505:in `call'
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:778:in `_run_save_callbacks'
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:81:in `run_callbacks'
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/active-fedora-9.1.2/lib/active_fedora/callbacks.rb:237:in `block in create_record'
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:117:in `call'
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:117:in `call'
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:505:in `call'
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:505:in `call'
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:778:in `_run_create_callbacks'
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:81:in `run_callbacks'
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/active-fedora-9.1.2/lib/active_fedora/callbacks.rb:236:in `create_record'
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/active-fedora-9.1.2/lib/active_fedora/persistence.rb:144:in `create_or_update'
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/active-fedora-9.1.2/lib/active_fedora/persistence.rb:27:in `save'
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/active-fedora-9.1.2/lib/active_fedora/validations.rb:50:in `save'
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/active-fedora-9.1.2/lib/active_fedora/persistence.rb:112:in `create'
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/sufia-models-6.3.0/app/models/batch.rb:23:in `safe_create'
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/sufia-models-6.3.0/app/models/batch.rb:15:in `rescue in find_or_create'
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/sufia-models-6.3.0/app/models/batch.rb:13:in `find_or_create'
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/sufia-6.3.0/app/controllers/concerns/sufia/files_controller_behavior.rb:226:in `process_file'
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/sufia-6.3.0/app/controllers/concerns/sufia/files_controller_behavior.rb:99:in `create_from_upload'
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/sufia-6.3.0/app/controllers/concerns/sufia/files_controller_behavior.rb:84:in `create'
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/sufia-6.3.0/app/controllers/concerns/sufia/files_controller/browse_everything.rb:9:in `create'
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/sufia-6.3.0/app/controllers/concerns/sufia/files_controller/local_ingest_behavior.rb:9:in `create'
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/actionpack-4.2.4/lib/abstract_controller/base.rb:198:in `process_action'
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_controller/metal/rendering.rb:10:in `process_action'
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/actionpack-4.2.4/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:117:in `call'
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:117:in `call'
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:505:in `call'
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:505:in `call'
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:81:in `run_callbacks'
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/actionpack-4.2.4/lib/abstract_controller/callbacks.rb:19:in `process_action'
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_controller/metal/rescue.rb:29:in `process_action'
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/notifications.rb:164:in `block in instrument'
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/notifications.rb:164:in `instrument'
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/actionpack-4.2.4/lib/abstract_controller/base.rb:137:in `process'
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/actionview-4.2.4/lib/action_view/rendering.rb:30:in `process'
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_controller/metal.rb:196:in `dispatch'
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_controller/metal.rb:237:in `block in action'
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:76:in `call'
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:76:in `call' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:76:in `dispatch' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:45:in `serve' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/journey/router.rb:43:in `block in serve' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/journey/router.rb:30:in `each' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/journey/router.rb:30:in `serve' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:821:in `call' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/railties-4.2.4/lib/rails/engine.rb:518:in `call' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/railties-4.2.4/lib/rails/railtie.rb:194:in `public_send' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/railties-4.2.4/lib/rails/railtie.rb:194:in `method_missing' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/mapper.rb:51:in `serve' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/journey/router.rb:43:in `block in serve' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/journey/router.rb:30:in `each' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/journey/router.rb:30:in `serve' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:821:in `call' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/newrelic_rpm-3.9.4.245/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/newrelic_rpm-3.9.4.245/lib/new_relic/rack/error_collector.rb:50:in `traced_call' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/newrelic_rpm-3.9.4.245/lib/new_relic/agent/instrumentation/middleware_tracing.rb:55:in `call' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/newrelic_rpm-3.9.4.245/lib/new_relic/rack/agent_hooks.rb:26:in `traced_call' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/newrelic_rpm-3.9.4.245/lib/new_relic/agent/instrumentation/middleware_tracing.rb:55:in `call' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/newrelic_rpm-3.9.4.245/lib/new_relic/rack/browser_monitoring.rb:23:in `traced_call' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/newrelic_rpm-3.9.4.245/lib/new_relic/agent/instrumentation/middleware_tracing.rb:55:in `call' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/warden-1.2.3/lib/warden/manager.rb:35:in `block in call' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `catch' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `call' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/newrelic_rpm-3.9.4.245/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/rack-1.6.4/lib/rack/etag.rb:24:in `call' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/newrelic_rpm-3.9.4.245/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/rack-1.6.4/lib/rack/conditionalget.rb:38:in `call' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/newrelic_rpm-3.9.4.245/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/newrelic_rpm-3.9.4.245/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/params_parser.rb:27:in `call' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/newrelic_rpm-3.9.4.245/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/flash.rb:260:in `call' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/newrelic_rpm-3.9.4.245/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/newrelic_rpm-3.9.4.245/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/cookies.rb:560:in `call' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/newrelic_rpm-3.9.4.245/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/query_cache.rb:36:in `call' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/newrelic_rpm-3.9.4.245/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/newrelic_rpm-3.9.4.245/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/active-fedora-9.1.2/lib/active_fedora/ldp_cache.rb:26:in `call' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/newrelic_rpm-3.9.4.245/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:88:in `__run_callbacks__' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:778:in `_run_call_callbacks' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:81:in `run_callbacks' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/callbacks.rb:27:in `call' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/newrelic_rpm-3.9.4.245/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/remote_ip.rb:78:in `call' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/newrelic_rpm-3.9.4.245/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/newrelic_rpm-3.9.4.245/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/newrelic_rpm-3.9.4.245/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/railties-4.2.4/lib/rails/rack/logger.rb:38:in `call_app' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/railties-4.2.4/lib/rails/rack/logger.rb:20:in `block in call' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/tagged_logging.rb:68:in `block in tagged' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/tagged_logging.rb:26:in `tagged' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/tagged_logging.rb:68:in `tagged' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/railties-4.2.4/lib/rails/rack/logger.rb:20:in `call' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/newrelic_rpm-3.9.4.245/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/request_id.rb:21:in `call' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/newrelic_rpm-3.9.4.245/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/newrelic_rpm-3.9.4.245/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/newrelic_rpm-3.9.4.245/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/newrelic_rpm-3.9.4.245/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/newrelic_rpm-3.9.4.245/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/railties-4.2.4/lib/rails/engine.rb:518:in `call' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/railties-4.2.4/lib/rails/application.rb:165:in `call' 
/var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/newrelic_rpm-3.9.4.245/lib/new_relic/agent/instrumentation/middleware_tracing.rb:57:in `call' 
/usr/share/gems/gems/passenger-4.0.56/lib/phusion_passenger/rack/thread_handler_extension.rb:74:in `process_request' 
/usr/share/gems/gems/passenger-4.0.56/lib/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request' 
/usr/share/gems/gems/passenger-4.0.56/lib/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop' 
/usr/share/gems/gems/passenger-4.0.56/lib/phusion_passenger/request_handler.rb:455:in `block (3 levels) in start_threads' 
```

**Comment by phebal** [comment]
This is potentially fixed in 6.4+ so closing until we see it again after upgrade
