### ISSUE TITLE
Some creator field queries cause errors

### ISSUE THREAD

**Issue by phebal** [galterlibrary/digital-repository#346]
Example:  https://digitalhub.northwestern.edu//authorities/generic_files/creator?q=Black%2C+G.+V.+(
```log
I, [2016-01-18T16:22:37.233748 #15994]  INFO -- : Started GET "/authorities/generic_files/creator?q=Black%2C+G.+V.+(G" for 73.209.168.208 at 2016-01-18 16:22:37 -0600
I, [2016-01-18T16:22:37.235344 #15994]  INFO -- : Processing by CustomAuthoritiesController#query_users as JSON
I, [2016-01-18T16:22:37.235415 #15994]  INFO -- :   Parameters: {"q"=>"Black, G. V. (G"}
I, [2016-01-18T16:22:37.315054 #15994]  INFO -- : Completed 500 Internal Server Error in 80ms (ActiveRecord: 2.6ms)
F, [2016-01-18T16:22:37.316815 #15994] FATAL -- :
RuntimeError (no result returned by search):
  app/models/nuldap.rb:70:in `search'
  app/models/nuldap.rb:70:in `multi_search'
  app/controllers/custom_authorities_controller.rb:69:in `query_users'
```

**Comment by phebal** [comment]
Also, related `/authorities/generic_files/verify_user?q=Black,%20G.%20V.%20(Greene%20Vardiman)` cause the same error
