### ISSUE TITLE
Problems characterizing CSV files, files end up not downloadable

### ISSUE THREAD

**Issue by phebal** [galterlibrary/digital-repository#450]
```
Ldp::HttpError: STATUS: 500 java.lang.RuntimeException: java.nio.charset.MalformedInputException: Input length = 1
        at org.apache.commons.csv.CSVParser$1.getNextRecord(CSVParser.java:398)
        at org.apache.commons.csv.CSVParser$1.hasNext(CSVParser.java:407)
        at org.apache.jena.atlas.iterator.Iter$4.hasNext(Iter.java:318)
        at org.apache.jena.riot.lang.LangCSV.parse(LangCSV.java:93)
        at org.apache.jena.riot.RDFParserRegistry$ReaderRIOTLang.read(RDFParserRegistry.java:185)
        at org.apache.jena.riot.RDFDataMgr.process(RDFDataMgr.java:906)
        at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:257)
        at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:243)
        at org.apache.jena.riot.adapters.RDFReaderRIOT.read(RDFReaderRIOT.java:70)
        at org.apache.jena.riot.adapters.RDFReaderRIOT_CSV.read(RDFReaderRIOT_CSV.java:43)
        at com.hp.hpl.jena.rdf.model.impl.ModelCom.read(ModelCom.java:277)
        at org.fcrepo.http.api.ContentExposingResource.getContent(ContentExposingResource.java:183)
        at org.fcrepo.http.api.FedoraLdp.describe(Fed...
```

**Comment by phebal** [comment]
And a full trace:
```
  ^[[4;32;1mResponse body^[[0m   ^[[0;1morg.apache.jena.riot.RiotException: <file:///staging/4e/3c/58/0e/4e3c580e-319d-4dae-9d8c-88f6fa1e721f/content/jcr:content {jcr:lastModifiedBy=bypassAdmin, jcr:uuid=a74de80f-a60c-4d40-8f92-6a74e3d3dccd, jcr:mimeType=text/plain, premis:hasSize=6945267, ebucore:hasMimeType=text/csv, jcr:createdBy=bypassAdmin, jcr:primaryType=nt:resource, jcr:created=2016-08-10T11:46:31.708-05:00, premis:hasMessageDigest=urn:sha1:e7de44aea6276cc3dd280f0bf2f5ff6d5267e0d1, jcr:mixinTypes=[fedora:Binary], jcr:lastModified=2016-08-10T11:46:31.708-05:00, ebucore:filename=users_20160510.csv, jcr:data=**binary-value-not-shown**}> Code: 0/ILLEGAL_CHARACTER in PATH: The character violates the grammar rules for URIs/IRIs.
        at org.apache.jena.riot.system.IRIResolver.exceptions(IRIResolver.java:311)
        at org.apache.jena.riot.system.IRIResolver.access$000(IRIResolver.java:31)
        at org.apache.jena.riot.system.IRIResolver$IRIResolverNormal.resolve(IRIResolver.java:414)
        at org.apache.jena.riot.system.IRIResolver$IRIResolverSync.resolve(IRIResolver.java:449)
        at org.apache.jena.riot.system.IRIResolver.resolveIRI(IRIResolver.java:190)
        at org.apache.jena.riot.system.IRIResolver.resolveString(IRIResolver.java:170)
        at org.apache.jena.riot.lang.LangCSV.parse(LangCSV.java:97)
        at org.apache.jena.riot.RDFParserRegistry$ReaderRIOTLang.read(RDFParserRegistry.java:185)
        at org.apache.jena.riot.RDFDataMgr.process(RDFDataMgr.java:906)
        at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:257)
        at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:243)
        at org.apache.jena.riot.adapters.RDFReaderRIOT.read(RDFReaderRIOT.java:70)
        at org.apache.jena.riot.adapters.RDFReaderRIOT_CSV.read(RDFReaderRIOT_CSV.java:43)
        at com.hp.hpl.jena.rdf.model.impl.ModelCom.read(ModelCom.java:277)
        at org.fcrepo.http.api.ContentExposingResource.getContent(ContentExposingResource.java:183)
        at org.fcrepo.http.api.FedoraLdp.describe(FedoraLdp.java:211)
        at sun.reflect.GeneratedMethodAccessor25.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:151)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(Abst

<some data truncated>

assfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1030)
        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:373)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:381)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:344)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:221)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:503)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:522)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
        at org.eclipse.jetty.server.Server.handle(Server.java:370)
        at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
        at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:971)
        at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1033)
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)
        at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
        at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by phebal** [comment]
And HTTP exchange that lead to the error:
```
  ^[[4;32;1mHTTP HEAD (17.01ms)^[[0m   ^[[0;1mhttp://localhost:8983/fedora/rest/staging/4e/3c/58/0e/4e3c580e-319d-4dae-9d8c-88f6fa1e721f/content^[[0m
  ^[[4;32;1mHTTP request header^[[0m   ^[[0;1mUser-Agent: Faraday v0.9.2^[[0m
  ^[[4;32;1mHTTP request header^[[0m   ^[[0;1mAuthorization: Basic ZmVkb3JhQWRtaW46ZmVkb3JhQWRtaW4=^[[0m
  ^[[4;32;1mHTTP request header^[[0m   ^[[0;1mAccept: */*^[[0m
  ^[[4;32;1mHTTP request header^[[0m   ^[[0;1mConnection: close^[[0m
  ^[[4;32;1mHTTP request header^[[0m   ^[[0;1mHost: localhost:8983^[[0m
  ^[[4;32;1mResponse status^[[0m   ^[[0;1mNet::HTTPOK (200)^[[0m
  ^[[4;32;1mHTTP response header^[[0m   ^[[0;1mEtag: "e5c881b8d5653ca36fdc8fa2ad25c7e372f9a2d8"^[[0m
  ^[[4;32;1mHTTP response header^[[0m   ^[[0;1mLast-Modified: Wed, 10 Aug 2016 16:46:31 GMT^[[0m
  ^[[4;32;1mHTTP response header^[[0m   ^[[0;1mContent-Length: 6945267^[[0m
  ^[[4;32;1mHTTP response header^[[0m   ^[[0;1mAccept-Ranges: bytes^[[0m
  ^[[4;32;1mHTTP response header^[[0m   ^[[0;1mContent-Disposition: attachment; filename="users_20160510.csv"; creation-date="Wed, 10 Aug 2016 16:46:31 GMT"; modification-date="Wed, 10 Aug 2016 16:46:31 GMT"; size=6945267^[[0m
  ^[[4;32;1mHTTP response header^[[0m   ^[[0;1mLink: <http://www.w3.org/ns/ldp#Resource>;rel="type", <http://www.w3.org/ns/ldp#NonRDFSource>;rel="type", <http://localhost:8983/fedora/rest/staging/4e/3c/58/0e/4e3c580e-319d-4dae-9d8c-88f6fa1e721f/content/fcr:metadata>; rel="describedby"^[[0m
  ^[[4;32;1mHTTP response header^[[0m   ^[[0;1mAllow: DELETE,HEAD,GET,PUT,OPTIONS^[[0m
  ^[[4;32;1mHTTP response header^[[0m   ^[[0;1mContent-Type: text/csv^[[0m
  ^[[4;32;1mHTTP response header^[[0m   ^[[0;1mConnection: close^[[0m
  ^[[4;32;1mHTTP GET (19.50ms)^[[0m   ^[[0;1mhttp://localhost:8983/fedora/rest/staging/4e/3c/58/0e/4e3c580e-319d-4dae-9d8c-88f6fa1e721f/content^[[0m
  ^[[4;32;1mHTTP request header^[[0m   ^[[0;1mUser-Agent: Faraday v0.9.2^[[0m
  ^[[4;32;1mHTTP request header^[[0m   ^[[0;1mAuthorization: Basic ZmVkb3JhQWRtaW46ZmVkb3JhQWRtaW4=^[[0m
  ^[[4;32;1mHTTP request header^[[0m   ^[[0;1mPrefer: return=representation^[[0m
  ^[[4;32;1mHTTP request header^[[0m   ^[[0;1mAccept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3^[[0m
  ^[[4;32;1mHTTP request header^[[0m   ^[[0;1mAccept: */*^[[0m
  ^[[4;32;1mHTTP request header^[[0m   ^[[0;1mConnection: close^[[0m
  ^[[4;32;1mHTTP request header^[[0m   ^[[0;1mHost: localhost:8983^[[0m
  ^[[4;32;1mResponse status^[[0m   ^[[0;1mNet::HTTPInternalServerError (500)^[[0m
  ^[[4;32;1mHTTP response header^[[0m   ^[[0;1mEtag: "e5c881b8d5653ca36fdc8fa2ad25c7e372f9a2d8"^[[0m
  ^[[4;32;1mHTTP response header^[[0m   ^[[0;1mLast-Modified: Wed, 10 Aug 2016 16:46:31 GMT^[[0m
  ^[[4;32;1mHTTP response header^[[0m   ^[[0;1mAccept-Ranges: bytes^[[0m
  ^[[4;32;1mHTTP response header^[[0m   ^[[0;1mContent-Disposition: attachment; filename="users_20160510.csv"; creation-date="Wed, 10 Aug 2016 16:46:31 GMT"; modification-date="Wed, 10 Aug 2016 16:46:31 GMT"; size=6945267^[[0m
  ^[[4;32;1mHTTP response header^[[0m   ^[[0;1mLink: <http://www.w3.org/ns/ldp#Resource>;rel="type", <http://www.w3.org/ns/ldp#NonRDFSource>;rel="type", <http://localhost:8983/fedora/rest/staging/4e/3c/58/0e/4e3c580e-319d-4dae-9d8c-88f6fa1e721f/content/fcr:metadata>; rel="describedby"^[[0m
  ^[[4;32;1mHTTP response header^[[0m   ^[[0;1mAllow: DELETE,HEAD,GET,PUT,OPTIONS^[[0m
  ^[[4;32;1mHTTP response header^[[0m   ^[[0;1mContent-Length: 6221^[[0m
  ^[[4;32;1mHTTP response header^[[0m   ^[[0;1mContent-Type: text/turtle^[[0m
  ^[[4;32;1mHTTP response header^[[0m   ^[[0;1mConnection: close^[[0m
```

**Comment by phebal** [comment]
https://jira.duraspace.org/browse/FCREPO-2093?filter=-4&jql=cf%5B10020%5D%20%3C%3D%20%2220%22%20AND%20cf%5B10020%5D%20%3E%3D%20%221%22%20ORDER%20BY%20createdDate%20DESC
