### ISSUE TITLE
New version of FITS is having frequent failures

### ISSUE THREAD

**Issue by phebal** [galterlibrary/digital-repository#480]
fits-1.0.1 is having problems starting up quite often. This came up during loading PNB volumes. The characterization would fail so much that even retrying would not help. Switching back to .8.x version fixed the issue. The 1.0.1 version comes with some fixes we want, but this is unacceptable and we need to switch back until it's fixed or figure out why it's happening.

**Comment by phebal** [comment]
```
  {"class"=>"Sufia::Resque::MarshaledJob", "args"=>["BAhvOhRDaGFyYWN0ZXJpemVKb2IGOghAaWRJIikzOTRjNWQ1Zi02Y2U1LTRj\nMWYtYWRhOS04ZmY4YTc2MzhmZTQGOgZFVA==\n"]}
Exception:
  Unable to execute command "/var/www/apps/fits-1.0.1/fits.sh -i "/tmp/content-1.pdf20160915-7072-1a24iul.pdf""
Exception in thread "main" edu.harvard.hul.ois.fits.exceptions.FitsToolException: Error loading native library for MediaInfo please check that fits_home is properly set
        at edu.harvard.hul.ois.fits.tools.mediainfo.MediaInfo.<init>(MediaInfo.java:92)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at edu.harvard.hul.ois.fits.tools.ToolBelt.init(ToolBelt.java:136)
        at edu.harvard.hul.ois.fits.tools.ToolBelt.<init>(ToolBelt.java:72)
        at edu.harvard.hul.ois.fits.Fits.<init>(Fits.java:239)
        at edu.harvard.hul.ois.fits.Fits.<init>(Fits.java:121)
        at edu.harvard.hul.ois.fits.Fits.<init>(Fits.java:110)
        at edu.harvard.hul.ois.fits.Fits.main(Fits.java:290)

  /var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/hydra-file_characterization-0.3.3/lib/hydra/file_characterization/characterizer.rb:51:in `internal_call'
  /var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/hydra-file_characterization-0.3.3/lib/hydra/file_characterization/characterizer.rb:70:in `output'
  /var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/hydra-file_characterization-0.3.3/lib/hydra/file_characterization/characterizer.rb:22:in `call'
  /var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/hydra-file_characterization-0.3.3/lib/hydra/file_characterization/characterizers.rb:24:in `characterize_with'
  /var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/hydra-file_characterization-0.3.3/lib/hydra/file_characterization.rb:114:in `block in run_characterizers_on_file'
  /var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/hydra-file_characterization-0.3.3/lib/hydra/file_characterization.rb:113:in `map'
  /var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/hydra-file_characterization-0.3.3/lib/hydra/file_characterization.rb:113:in `run_characterizers_on_file'
  /var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/hydra-file_characterization-0.3.3/lib/hydra/file_characterization.rb:107:in `block in run_characterizers'
  /var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/hydra-file_characterization-0.3.3/lib/hydra/file_characterization/to_temp_file.rb:28:in `call'
  /var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/hydra-file_characterization-0.3.3/lib/hydra/file_characterization/to_temp_file.rb:9:in `open'
  /var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/hydra-file_characterization-0.3.3/lib/hydra/file_characterization.rb:106:in `run_characterizers'
  /var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/hydra-file_characterization-0.3.3/lib/hydra/file_characterization.rb:70:in `characterize'
  /var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/hydra-derivatives-1.2.1/lib/hydra/derivatives/extract_metadata.rb:10:in `extract_metadata'
  /var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/sufia-models-6.6.1/app/models/concerns/sufia/generic_file/characterization.rb:73:in `characterize'
  /var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/sufia-models-6.6.1/app/jobs/characterize_job.rb:7:in `run'
  /var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/sufia-models-6.6.1/lib/sufia/models/resque.rb:32:in `perform'
  /var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/resque-1.26.0/lib/resque/job.rb:177:in `block (3 levels) in perform'
  /var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/newrelic_rpm-3.16.1.320/lib/new_relic/agent/instrumentation/resque.rb:41:in `block in around_perform_with_monitoring'
  /var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/newrelic_rpm-3.16.1.320/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:363:in `perform_action_with_newrelic_trace'
  /var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/newrelic_rpm-3.16.1.320/lib/new_relic/agent/instrumentation/resque.rb:33:in `around_perform_with_monitoring'
  /var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/resque-1.26.0/lib/resque/job.rb:176:in `block (2 levels) in perform'
  /var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/resque-1.26.0/lib/resque/job.rb:184:in `call'
  /var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/resque-1.26.0/lib/resque/job.rb:184:in `perform'
  /var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/resque-1.26.0/lib/resque/worker.rb:290:in `perform'
  /var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/resque-1.26.0/lib/resque/worker.rb:229:in `block in work'
  /var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/resque-1.26.0/lib/resque/worker.rb:206:in `loop'
  /var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/resque-1.26.0/lib/resque/worker.rb:206:in `work'
  /var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/resque-pool-0.6.0/lib/resque/pool.rb:396:in `block in spawn_worker!'
  /var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/resque-pool-0.6.0/lib/resque/pool.rb:389:in `fork'
  /var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/resque-pool-0.6.0/lib/resque/pool.rb:389:in `spawn_worker!'
  /var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/resque-pool-0.6.0/lib/resque/pool.rb:367:in `block in spawn_missing_workers_for'
  /var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/resque-pool-0.6.0/lib/resque/pool.rb:366:in `times'
  /var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/resque-pool-0.6.0/lib/resque/pool.rb:366:in `spawn_missing_workers_for'
  /var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/resque-pool-0.6.0/lib/resque/pool.rb:352:in `block in maintain_worker_count'
  /var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/resque-pool-0.6.0/lib/resque/pool.rb:350:in `each'
  /var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/resque-pool-0.6.0/lib/resque/pool.rb:350:in `maintain_worker_count'
  /var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/resque-pool-0.6.0/lib/resque/pool.rb:263:in `start'
  /var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/resque-pool-0.6.0/lib/resque/pool.rb:89:in `run'
  /var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/resque-pool-0.6.0/lib/resque/pool/tasks.rb:17:in `block (2 levels) in <top (required)>'
  /var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/rake-11.2.2/lib/rake/task.rb:248:in `call'
  /var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/rake-11.2.2/lib/rake/task.rb:248:in `block in execute'
  /var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/rake-11.2.2/lib/rake/task.rb:243:in `each'
  /var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/rake-11.2.2/lib/rake/task.rb:243:in `execute'
  /var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/rake-11.2.2/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
  /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
  /var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/rake-11.2.2/lib/rake/task.rb:180:in `invoke_with_call_chain'
  /var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/rake-11.2.2/lib/rake/task.rb:173:in `invoke'
  /var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/resque-pool-0.6.0/lib/resque/pool/cli.rb:148:in `start_pool'
  /var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/resque-pool-0.6.0/lib/resque/pool/cli.rb:20:in `run'
  /var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/gems/resque-pool-0.6.0/bin/resque-pool:7:in `<top (required)>'
  /var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/bin/resque-pool:23:in `load'
  /var/www/apps/galter_digital_repo/shared/gems/ruby/2.2.0/bin/resque-pool:23:in `<main>'
```

**Comment by phebal** [comment]
1186089 did not fix the issue

Real fix is to set the library path like this when running `fits.sh`:
`LD_LIBRARY_PATH=/var/www/apps/fits-1.0.3/tools/mediainfo/linux`

The tool has trouble figuring it out after loading `libzen.so.0`, it tries `/var/www/apps/fits-1.0.3/linux-x86-64/libmediainfo.so` and `/var/www/apps/fits-1.0.3/libmediainfo.so` then throws an error. It only happens occasionally on fast machines and very often on slow machines.

**Comment by phebal** [comment]
Opened a bug with upstream:
https://github.com/harvard-lts/fits/issues/120
