### ISSUE TITLE
Error when trying to view files

### ISSUE THREAD

**Issue by sharpattack** [galterlibrary/digital-repository#663]
Gabrielle is experiencing issues when trying to view "My Files" from the dashboard. 

Full error in log. 

```ActionView::Template::Error ():
    1: <ul class="facet-values list-unstyled">
    2:   <% paginator = facet_paginator(facet_field, display_facet) %>
    3:   <%= render_facet_limit_list paginator, solr_field %>
    4:
    5:   <% unless paginator.last_page? || params[:action] == "facet" %>
    6:     <li class="more_facets_link"><%= link_to 'more ' + facet_field.label.pluralize + '»',
  ldp (0.4.1) lib/ldp/client/methods.rb:121:in `block in check_for_errors'
  ldp (0.4.1) lib/ldp/client/methods.rb:119:in `tap'
  ldp (0.4.1) lib/ldp/client/methods.rb:119:in `check_for_errors'
  ldp (0.4.1) lib/ldp/client/methods.rb:25:in `block in head'
  activesupport (4.2.7) lib/active_support/notifications.rb:166:in `instrument'
  ldp (0.4.1) lib/ldp/client/methods.rb:17:in `head'
  ldp (0.4.1) lib/ldp/resource.rb:48:in `head'
  ldp (0.4.1) lib/ldp/resource.rb:31:in `new?'
  active-fedora (9.7.2) lib/active_fedora/relation/finder_methods.rb:187:in `load_from_fedora'
  active-fedora (9.7.2) lib/active_fedora/relation/finder_methods.rb:174:in `find_one'
  active-fedora (9.7.2) lib/active_fedora/relation/finder_methods.rb:233:in `find_with_ids'
  active-fedora (9.7.2) lib/active_fedora/relation/finder_methods.rb:58:in `find'
  active-fedora (9.7.2) lib/active_fedora/querying.rb:3:in `find'
  hydra-collections (5.0.3) app/helpers/collections_search_helper.rb:8:in `collection_name'
  blacklight (5.18.0) app/helpers/blacklight/facets_helper_behavior.rb:216:in `facet_display_value'
  blacklight (5.18.0) app/helpers/blacklight/facets_helper_behavior.rb:127:in `block in render_facet_value'
  actionview (4.2.7) lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
  actionview (4.2.7) lib/action_view/helpers/capture_helper.rb:202:in `with_output_buffer'
  haml (4.0.7) lib/haml/helpers/action_view_xss_mods.rb:5:in `with_output_buffer_with_haml_xss'
  actionview (4.2.7) lib/action_view/helpers/capture_helper.rb:38:in `capture'
  haml (4.0.7) lib/haml/helpers/action_view_mods.rb:52:in `capture_with_haml'
  actionview (4.2.7) lib/action_view/helpers/tag_helper.rb:106:in `content_tag'
  haml (4.0.7) lib/haml/helpers/action_view_mods.rb:61:in `content_tag_with_haml'
  blacklight (5.18.0) app/helpers/blacklight/facets_helper_behavior.rb:126:in `render_facet_value'
  blacklight (5.18.0) app/helpers/blacklight/facets_helper_behavior.rb:70:in `render_facet_item'
  blacklight (5.18.0) app/helpers/blacklight/facets_helper_behavior.rb:59:in `block in render_facet_limit_list'
  blacklight (5.18.0) app/helpers/blacklight/facets_helper_behavior.rb:59:in `map'
  blacklight (5.18.0) app/helpers/blacklight/facets_helper_behavior.rb:59:in `render_facet_limit_list'
  sufia (6.6.1) app/views/my/_facet_limit.html.erb:3:in `__var_www_apps_galter_digital_repo_shared_gems_ruby_______gems_sufia_______app_views_my__facet_limit_html_erb__2136992715836582231_88952120'
  actionview (4.2.7) lib/action_view/template.rb:145:in `block in render'
  activesupport (4.2.7) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.7) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.7) lib/active_support/notifications.rb:164:in `instrument'
  actionview (4.2.7) lib/action_view/template.rb:333:in `instrument'
  actionview (4.2.7) lib/action_view/template.rb:143:in `render'
  actionview (4.2.7) lib/action_view/renderer/partial_renderer.rb:339:in `render_partial'
  actionview (4.2.7) lib/action_view/renderer/partial_renderer.rb:310:in `block in render'
  actionview (4.2.7) lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
  activesupport (4.2.7) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.7) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.7) lib/active_support/notifications.rb:164:in `instrument'
  actionview (4.2.7) lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
  actionview (4.2.7) lib/action_view/renderer/partial_renderer.rb:309:in `render'
  actionview (4.2.7) lib/action_view/renderer/renderer.rb:51:in `render_partial'
  actionview (4.2.7) lib/action_view/renderer/renderer.rb:25:in `render'
  actionview (4.2.7) lib/action_view/helpers/rendering_helper.rb:32:in `render'
  haml (4.0.7) lib/haml/helpers/action_view_mods.rb:12:in `render_with_haml'
  blacklight (5.18.0) app/helpers/blacklight/facets_helper_behavior.rb:50:in `render_facet_limit'
  blacklight (5.18.0) app/helpers/blacklight/facets_helper_behavior.rb:23:in `block in render_facet_partials'
  blacklight (5.18.0) app/helpers/blacklight/facets_helper_behavior.rb:22:in `map'
  blacklight (5.18.0) app/helpers/blacklight/facets_helper_behavior.rb:22:in `render_facet_partials'
  sufia (6.6.1) app/views/my/_facets.html.erb:15:in `__var_www_apps_galter_digital_repo_shared_gems_ruby_______gems_sufia_______app_views_my__facets_html_erb___482423943960853985_89668440'
  actionview (4.2.7) lib/action_view/template.rb:145:in `block in render'
  activesupport (4.2.7) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.7) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.7) lib/active_support/notifications.rb:164:in `instrument'
  actionview (4.2.7) lib/action_view/template.rb:333:in `instrument'
  actionview (4.2.7) lib/action_view/template.rb:143:in `render'
  actionview (4.2.7) lib/action_view/renderer/partial_renderer.rb:339:in `render_partial'
  actionview (4.2.7) lib/action_view/renderer/partial_renderer.rb:310:in `block in render'
  actionview (4.2.7) lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
  activesupport (4.2.7) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.7) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.7) lib/active_support/notifications.rb:164:in `instrument'
  actionview (4.2.7) lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
  actionview (4.2.7) lib/action_view/renderer/partial_renderer.rb:309:in `render'
  actionview (4.2.7) lib/action_view/renderer/renderer.rb:51:in `render_partial'
  actionview (4.2.7) lib/action_view/renderer/renderer.rb:25:in `render'
  actionview (4.2.7) lib/action_view/helpers/rendering_helper.rb:32:in `render'
  haml (4.0.7) lib/haml/helpers/action_view_mods.rb:12:in `render_with_haml'
  sufia (6.6.1) app/views/my/index.html.erb:39:in `block in __var_www_apps_galter_digital_repo_shared_gems_ruby_______gems_sufia_______app_views_my_index_html_erb__4505390354995044752_89405820'
  actionview (4.2.7) lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
  actionview (4.2.7) lib/action_view/helpers/capture_helper.rb:202:in `with_output_buffer'
  haml (4.0.7) lib/haml/helpers/action_view_xss_mods.rb:5:in `with_output_buffer_with_haml_xss'
  actionview (4.2.7) lib/action_view/helpers/capture_helper.rb:38:in `capture'
  haml (4.0.7) lib/haml/helpers/action_view_mods.rb:52:in `capture_with_haml'
  actionview (4.2.7) lib/action_view/helpers/capture_helper.rb:152:in `content_for'
  sufia (6.6.1) app/views/my/index.html.erb:35:in `__var_www_apps_galter_digital_repo_shared_gems_ruby_______gems_sufia_______app_views_my_index_html_erb__4505390354995044752_89405820'
  actionview (4.2.7) lib/action_view/template.rb:145:in `block in render'
  activesupport (4.2.7) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.7) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.7) lib/active_support/notifications.rb:164:in `instrument'
  actionview (4.2.7) lib/action_view/template.rb:333:in `instrument'
  actionview (4.2.7) lib/action_view/template.rb:143:in `render'
  actionview (4.2.7) lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
  actionview (4.2.7) lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
activesupport (4.2.7) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.7) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.7) lib/active_support/notifications.rb:164:in `instrument'
  actionview (4.2.7) lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
  actionview (4.2.7) lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
  actionview (4.2.7) lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
  actionview (4.2.7) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
  actionview (4.2.7) lib/action_view/renderer/template_renderer.rb:14:in `render'
  actionview (4.2.7) lib/action_view/renderer/renderer.rb:46:in `render_template'
  actionview (4.2.7) lib/action_view/renderer/renderer.rb:27:in `render'
  actionview (4.2.7) lib/action_view/rendering.rb:100:in `_render_template'
  actionpack (4.2.7) lib/action_controller/metal/streaming.rb:217:in `_render_template'
  actionview (4.2.7) lib/action_view/rendering.rb:83:in `render_to_body'
  actionpack (4.2.7) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
  actionpack (4.2.7) lib/action_controller/metal/renderers.rb:37:in `render_to_body'
  actionpack (4.2.7) lib/abstract_controller/rendering.rb:25:in `render'
  actionpack (4.2.7) lib/action_controller/metal/rendering.rb:16:in `render'
  actionpack (4.2.7) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
  activesupport (4.2.7) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
  /home/deploy/.rvm/rubies/ruby-2.3.7/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
  activesupport (4.2.7) lib/active_support/core_ext/benchmark.rb:12:in `ms'
  actionpack (4.2.7) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
  actionpack (4.2.7) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
  activerecord (4.2.7) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
  actionpack (4.2.7) lib/action_controller/metal/instrumentation.rb:43:in `render'
  actionpack (4.2.7) lib/action_controller/metal/implicit_render.rb:10:in `default_render'
  actionpack (4.2.7) lib/action_controller/metal/implicit_render.rb:5:in `send_action'
  actionpack (4.2.7) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.7) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.7) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.7) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.7) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
  activesupport (4.2.7) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.7) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  activesupport (4.2.7) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
  activesupport (4.2.7) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.7) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.7) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.7) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.7) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.7) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.7) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.7) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.7) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.7) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.7) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.7) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.7) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.7) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.7) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.7) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
  actionpack (4.2.7) lib/action_dispatch/routing/route_set.rb:43:in `serve'
  actionpack (4.2.7) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.7) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.7) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.7) lib/action_dispatch/routing/route_set.rb:817:in `call'
  railties (4.2.7) lib/rails/engine.rb:518:in `call'
  railties (4.2.7) lib/rails/railtie.rb:194:in `public_send'
  railties (4.2.7) lib/rails/railtie.rb:194:in `method_missing'
  actionpack (4.2.7) lib/action_dispatch/routing/mapper.rb:51:in `serve'
  actionpack (4.2.7) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.7) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.7) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.7) lib/action_dispatch/routing/route_set.rb:817:in `call'
  newrelic_rpm (3.16.1.320) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  omniauth (1.8.1) lib/omniauth/strategy.rb:190:in `call!'
  omniauth (1.8.1) lib/omniauth/strategy.rb:168:in `call'
  newrelic_rpm (3.16.1.320) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  browser (2.2.0) lib/browser/middleware.rb:53:in `run_app'
  browser (2.2.0) lib/browser/middleware.rb:33:in `call'
  newrelic_rpm (3.16.1.320) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  newrelic_rpm (3.16.1.320) lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
  newrelic_rpm (3.16.1.320) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  newrelic_rpm (3.16.1.320) lib/new_relic/rack/browser_monitoring.rb:32:in `traced_call'
  newrelic_rpm (3.16.1.320) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
  warden (1.2.7) lib/warden/manager.rb:35:in `catch'
  warden (1.2.7) lib/warden/manager.rb:35:in `call'
  newrelic_rpm (3.16.1.320) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.6.10) lib/rack/etag.rb:24:in `call'
  newrelic_rpm (3.16.1.320) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.6.10) lib/rack/conditionalget.rb:25:in `call'
  newrelic_rpm (3.16.1.320) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.6.10) lib/rack/head.rb:13:in `call'
  newrelic_rpm (3.16.1.320) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (4.2.7) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  newrelic_rpm (3.16.1.320) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (4.2.7) lib/action_dispatch/middleware/flash.rb:260:in `call'
newrelic_rpm (3.16.1.320) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.6.10) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.10) lib/rack/session/abstract/id.rb:220:in `call'
  newrelic_rpm (3.16.1.320) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (4.2.7) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  newrelic_rpm (3.16.1.320) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  activerecord (4.2.7) lib/active_record/query_cache.rb:36:in `call'
  newrelic_rpm (3.16.1.320) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  activerecord (4.2.7) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  newrelic_rpm (3.16.1.320) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  active-fedora (9.7.2) lib/active_fedora/ldp_cache.rb:26:in `call'
  newrelic_rpm (3.16.1.320) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (4.2.7) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.7) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  activesupport (4.2.7) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  activesupport (4.2.7) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.7) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  newrelic_rpm (3.16.1.320) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (4.2.7) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  newrelic_rpm (3.16.1.320) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (4.2.7) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  newrelic_rpm (3.16.1.320) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (4.2.7) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  newrelic_rpm (3.16.1.320) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  railties (4.2.7) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.7) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.7) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.7) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.7) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.7) lib/rails/rack/logger.rb:20:in `call'
  newrelic_rpm (3.16.1.320) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (4.2.7) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  newrelic_rpm (3.16.1.320) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.6.10) lib/rack/methodoverride.rb:22:in `call'
  newrelic_rpm (3.16.1.320) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.6.10) lib/rack/runtime.rb:18:in `call'
  newrelic_rpm (3.16.1.320) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  activesupport (4.2.7) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  newrelic_rpm (3.16.1.320) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.6.10) lib/rack/sendfile.rb:113:in `call'
  newrelic_rpm (3.16.1.320) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (4.2.7) lib/action_dispatch/middleware/ssl.rb:24:in `call'
  newrelic_rpm (3.16.1.320) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  railties (4.2.7) lib/rails/engine.rb:518:in `call'
  railties (4.2.7) lib/rails/application.rb:165:in `call'
  newrelic_rpm (3.16.1.320) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  passenger (5.2.3) src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
  passenger (5.2.3) src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:152:in `accept_and_process_next_request'
  passenger (5.2.3) src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
  passenger (5.2.3) src/ruby_supportlib/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
  passenger (5.2.3) src/ruby_supportlib/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'```

**Comment by sharpattack** [comment]
Finally resolved. Horrible issue that took me days to investigate. This was not easy to debug, but was eventually able to narrow it down to a few suspect files. 

More detailed notes coming.

**Comment by sharpattack** [comment]
Notes: 

After inspecting all of Gabrielle's deposits looking for an anomaly, I was able to drill down to a theory. I noticed there were several deposits that were identical; same uploaded file, same metadata such as title and keywords, and same visibility set to "Open Access". Removing one of the two identical deposits, and any of it's multiple related files, resolved this error.
